### ISSUE TITLE
aoihttp 3.10.6 leads to failure

### ISSUE THREAD

**Issue by hrvg** [hyriver/async-retriever#48]
### What happened?

I noticed today failure when testing a service relying on `py3dep`. After some investigation, the issue comes from `async_retriever` and its dependency on `aiohttp`.

### What did you expect to happen?

I expected `py3dep` to be working.

### Minimal Complete Verifiable Example

```Python
import py3dep
bbox = (-78.0, 39.2, -78.2, 39.1)
dem = py3dep.get_map("DEM", bbox, 1)

# The actual issue is displayed when running:
from pygeoogc import ServiceURL
from pygeoogc import utils as ogc_utils
wms_url = ServiceURL().wms.nm_3dep
valid_crs = ogc_utils.valid_wms_crs(wms_url)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/redacted/path/lib/python3.12/site-packages/pygeoogc/utils.py", line 862, in valid_wms_crs
    root = ETree.fromstring(ar.retrieve_text([url], [kwds], ssl=False)[0])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/redacted/path/lib/python3.12/site-packages/async_retriever/async_retriever.py", line 500, in retrieve_text
    return retrieve(
           ^^^^^^^^^
  File "/redacted/path/lib/python3.12/site-packages/async_retriever/async_retriever.py", line 433, in retrieve
    resp = [r for _, r in sorted(tlz.concat(results))]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/redacted/path/lib/python3.12/site-packages/async_retriever/async_retriever.py", line 431, in <genexpr>
    results = (loop.run_until_complete(session(url_kwds=c)) for c in chunked_reqs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/redacted/path/lib/python3.12/site-packages/async_retriever/async_retriever.py", line 236, in async_session_with_cache
    return await asyncio.gather(*tasks)  # pyright: ignore[reportReturnType]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/redacted/path/lib/python3.12/site-packages/async_retriever/_utils.py", line 81, in retriever
    async with session(url, **s_kwds) as response:
  File "/redacted/path/lib/python3.12/site-packages/aiohttp/client.py", line 1364, in __aexit__
    await self._resp.__aexit__(exc_type, exc, tb)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CachedResponse' object has no attribute '__aexit__'. Did you mean: '__init__'?
```

### Anything else we need to know?

Changing this line

https://github.com/hyriver/async-retriever/blob/c2c7d2314dbec42b8df1235dd78d148c1f0adf1c/pyproject.toml#L37

to:

```
 "aiohttp[speedups]>=3.8.3,<=3.10.5" 
```

 may solve the issue.

### Environment

<details>

SYS INFO
--------
commit: None
python: 3.12.5 (main, Aug 17 2024, 16:46:05) [GCC 11.4.0]
python-bits: 64
OS: Linux
OS-release: 6.9.3-76060903-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')

PACKAGE                VERSION
-------------------------------
async-retriever        0.17.1
pygeoogc               0.17.1
pygeoutils             0.17.1
py3dep                 0.17.1
pynhd                  N/A
pygridmet              N/A
pydaymet               N/A
hydrosignatures        N/A
pynldas2               N/A
pygeohydro             N/A
aiohttp                3.10.6
aiohttp-client-cache   0.11.1
aiosqlite              0.20.0
cytoolz                0.12.3
ujson                  5.10.0
defusedxml             0.7.1
joblib                 1.4.2
multidict              6.1.0
owslib                 0.31.0
pyproj                 3.6.1
requests               2.32.3
requests-cache         1.2.1
shapely                2.0.6
url-normalize          1.4.3
urllib3                2.2.3
yarl                   1.12.1
geopandas              1.0.1
netcdf4                1.7.1.post2
numpy                  2.1.1
rasterio               1.3.11
rioxarray              0.17.0
scipy                  1.14.1
xarray                 2024.9.0
click                  8.1.7
pyflwdir               N/A
networkx               N/A
pyarrow                N/A
folium                 N/A
h5netcdf               N/A
matplotlib             N/A
pandas                 2.2.3
numba                  N/A
bottleneck             N/A
py7zr                  N/A
pyogrio                0.9.0
-------------------------------

</details>

**Comment by cheginit** [comment]
Thanks for taking the time to figure out the issue. It seems the issue is caused by [`aiohttp-client-cache`](https://github.com/requests-cache/aiohttp-client-cache/issues/251). It's being addressed soon. Once it's done, updating `aiohttp-client-cache` should fix the issue. I will then release a new version to pin the dep on `aiohttp-client-cache` to the fixed version.

**Comment by cheginit** [comment]
BTW, until it gets fixed, as a workaround, you can disable caching by:

```python
import os

os.environ["HYRIVER_CACHE_DISABLE"] = "true"
```

This should fix the issue at the expense of missing caching.

**Comment by hrvg** [comment]
> BTW, until it gets fixed, as a workaround, you can disable caching by:
> 
> ```python
> import os
> 
> os.environ["HYRIVER_CACHE_DISABLE"] = "true"
> ```
> 
> This should fix the issue at the expense of missing caching.

Thanks, that's good to know! I just downgraded do 3.10.5 to get `py3dep` to function again.

**Comment by alessio-locatelli** [comment]
@cheginit The correct fix was released yesterday: https://pypi.org/project/aiohttp-client-cache/0.12.3/ Please update. Sorry for the delay.

**Comment by cheginit** [comment]
@alessio-locatelli Thanks for addressing the issue and letting me know about the update. I will release a new version too.

**Comment by cheginit** [comment]
@hrvg and @rmcd-mscb, HyRiver 0.18 is out now that fixes this issue.

**Comment by cheginit** [comment]
Please reopen if you still have this issue.

**Comment by hrvg** [comment]
> @hrvg and @rmcd-mscb, HyRiver 0.18 is out now that fixes this issue.

Late to the party, but I confirm that unpinning `aoihttp` (from `3.10.5`) led to a green build on our end ✅
